/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vistas;

/**
 *
 * @author bruno
 */
public class Carga_reservas extends javax.swing.JInternalFrame {

    /**
     * Creates new form Carga_reservas
     */
    public Carga_reservas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_CargarReservas = new javax.swing.JLabel();
        jLabel_SeleccionarHorario = new javax.swing.JLabel();
        jLabel_DatosCliente = new javax.swing.JLabel();
        jLabel_Nombre = new javax.swing.JLabel();
        jLabel_DNI = new javax.swing.JLabel();
        jButton_Limpiar = new javax.swing.JButton();
        jButton_CrearReserva = new javax.swing.JButton();
        jTextField_Nombre = new javax.swing.JTextField();
        jTextField_DNI = new javax.swing.JTextField();
        jLabel_SeleccionarDia = new javax.swing.JLabel();
        jLabel_SeleccionarCantidad = new javax.swing.JLabel();
        jComboBox_CantidadPersonas = new javax.swing.JComboBox<>();

        jLabel_CargarReservas.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel_CargarReservas.setText("Cargar reservas");

        jLabel_SeleccionarHorario.setText("Seleccione un horario");

        jLabel_DatosCliente.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel_DatosCliente.setText("Datos cliente");

        jLabel_Nombre.setText("Nombre");

        jLabel_DNI.setText("DNI");

        jButton_Limpiar.setText("Limpiar");

        jButton_CrearReserva.setText("Crear reserva");
        jButton_CrearReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CrearReservaActionPerformed(evt);
            }
        });

        jLabel_SeleccionarDia.setText("Seleccione un día");

        jLabel_SeleccionarCantidad.setText("Seleccione cantidad personas");

        jComboBox_CantidadPersonas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(156, 156, 156)
                            .addComponent(jLabel_DatosCliente))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(78, 78, 78)
                            .addComponent(jButton_Limpiar)
                            .addGap(87, 87, 87)
                            .addComponent(jButton_CrearReserva))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(117, 117, 117)
                            .addComponent(jLabel_CargarReservas))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(53, 53, 53)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel_DNI)
                                .addComponent(jLabel_Nombre))
                            .addGap(86, 86, 86)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextField_Nombre)
                                .addComponent(jTextField_DNI, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_SeleccionarDia)
                            .addComponent(jLabel_SeleccionarHorario)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel_SeleccionarCantidad)
                                .addGap(40, 40, 40)
                                .addComponent(jComboBox_CantidadPersonas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel_CargarReservas)
                .addGap(38, 38, 38)
                .addComponent(jLabel_SeleccionarDia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addComponent(jLabel_SeleccionarHorario)
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_SeleccionarCantidad, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jComboBox_CantidadPersonas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addComponent(jLabel_DatosCliente)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Nombre)
                    .addComponent(jTextField_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_DNI)
                    .addComponent(jTextField_DNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Limpiar)
                    .addComponent(jButton_CrearReserva))
                .addGap(43, 43, 43))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_CrearReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CrearReservaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_CrearReservaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_CrearReserva;
    private javax.swing.JButton jButton_Limpiar;
    private javax.swing.JComboBox<String> jComboBox_CantidadPersonas;
    private javax.swing.JLabel jLabel_CargarReservas;
    private javax.swing.JLabel jLabel_DNI;
    private javax.swing.JLabel jLabel_DatosCliente;
    private javax.swing.JLabel jLabel_Nombre;
    private javax.swing.JLabel jLabel_SeleccionarCantidad;
    private javax.swing.JLabel jLabel_SeleccionarDia;
    private javax.swing.JLabel jLabel_SeleccionarHorario;
    private javax.swing.JTextField jTextField_DNI;
    private javax.swing.JTextField jTextField_Nombre;
    // End of variables declaration//GEN-END:variables
}
