/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;
import java.util.HashSet;
import java.util.Set;
import javax.swing.ImageIcon;
import javax.swing.JFrame;

/**
 *
 * @author bruno
 */
public class Menu_principal extends javax.swing.JFrame {


    /**
     * Creates new form Menu_principal
     */
    public Menu_principal() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ImageIcon icono = new ImageIcon(getClass().getResource("/recursos/fondo.png"));
        Image fondo = icono.getImage();
        escritorio = new javax.swing.JDesktopPane(){

            public void paintComponent(Graphics g){
                g.drawImage(fondo,0,0,getWidth(),getHeight(),this);
            }
        };
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu_Pedidos = new javax.swing.JMenu();
        jMenuItem_CrearPedi = new javax.swing.JMenuItem();
        jMenuItem_CobrarPedi = new javax.swing.JMenuItem();
        jMenuItem_Ganancias = new javax.swing.JMenuItem();
        jMenu_Reservas = new javax.swing.JMenu();
        jMenuItemReservas = new javax.swing.JMenuItem();
        jMenuItemAnularReservas = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemCargaMozo = new javax.swing.JMenuItem();
        jMenuItemEliminarMozo = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(450, 650));

        escritorio.setBackground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 546, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 670, Short.MAX_VALUE)
        );

        jMenu_Pedidos.setText("Pedidos");
        jMenu_Pedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu_PedidosActionPerformed(evt);
            }
        });

        jMenuItem_CrearPedi.setText("Tomar pedido");
        jMenuItem_CrearPedi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_CrearPediActionPerformed(evt);
            }
        });
        jMenu_Pedidos.add(jMenuItem_CrearPedi);

        jMenuItem_CobrarPedi.setText("Cancelar/cobrar pedido");
        jMenuItem_CobrarPedi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_CobrarPediActionPerformed(evt);
            }
        });
        jMenu_Pedidos.add(jMenuItem_CobrarPedi);

        jMenuItem_Ganancias.setText("Ganancias por día");
        jMenuItem_Ganancias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_GananciasActionPerformed(evt);
            }
        });
        jMenu_Pedidos.add(jMenuItem_Ganancias);

        jMenuBar1.add(jMenu_Pedidos);

        jMenu_Reservas.setText("Reservas");

        jMenuItemReservas.setText("Alta/Baja Reservas");
        jMenuItemReservas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemReservasActionPerformed(evt);
            }
        });
        jMenu_Reservas.add(jMenuItemReservas);

        jMenuItemAnularReservas.setText("Anular Reservas");
        jMenuItemAnularReservas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAnularReservasActionPerformed(evt);
            }
        });
        jMenu_Reservas.add(jMenuItemAnularReservas);

        jMenuItem1.setText("Listar Reservas");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu_Reservas.add(jMenuItem1);

        jMenuBar1.add(jMenu_Reservas);

        jMenu1.setText("Mozos");

        jMenuItemCargaMozo.setText("Cargar Mozo");
        jMenuItemCargaMozo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCargaMozoActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemCargaMozo);

        jMenuItemEliminarMozo.setText("Eliminar/Listar Mozos");
        jMenuItemEliminarMozo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemEliminarMozoActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemEliminarMozo);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(escritorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu_PedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu_PedidosActionPerformed
        // TODO add your handling code here:
              
    }//GEN-LAST:event_jMenu_PedidosActionPerformed

    private void jMenuItem_CrearPediActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_CrearPediActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
        
        Carga_pedidos pedidos = new Carga_pedidos();
        pedidos.setVisible(true);
        pedidos.getContentPane().setBackground(Color.darkGray);
        escritorio.add(pedidos);  
        
        try {
            pedidos.setMaximum(true);
        } catch (Exception e) {
            e.printStackTrace();
        }

        setLocationRelativeTo(null);
    }//GEN-LAST:event_jMenuItem_CrearPediActionPerformed

    private void jMenuItem_CobrarPediActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_CobrarPediActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
        Procesar_Pedido pedidos = new Procesar_Pedido();
        pedidos.setVisible(true);
        pedidos.getContentPane().setBackground(Color.darkGray);
        escritorio.add(pedidos);  
        
        try {
            pedidos.setMaximum(true);
        } catch (Exception e) {
            e.printStackTrace();
        }

        setLocationRelativeTo(null);
    }//GEN-LAST:event_jMenuItem_CobrarPediActionPerformed

    private void jMenuItemReservasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemReservasActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        Carga_reservas reservas = new Carga_reservas();
        reservas.setVisible(true);
        escritorio.add(reservas);
        escritorio.moveToFront(reservas);  
        
    }//GEN-LAST:event_jMenuItemReservasActionPerformed

    private void jMenuItem_GananciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_GananciasActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
        Ganancias ganacias = new Ganancias();
        ganacias.setVisible(true);
        ganacias.getContentPane().setBackground(Color.darkGray);
        escritorio.add(ganacias);
        escritorio.moveToFront(ganacias);  
        
        try {
            ganacias.setMaximum(true);
        } catch (Exception e) {
            e.printStackTrace();
        }
        
        setLocationRelativeTo(null);
    }//GEN-LAST:event_jMenuItem_GananciasActionPerformed

    private void jMenuItemAnularReservasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAnularReservasActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        Modificar_Eliminar_Reserva reservas = new Modificar_Eliminar_Reserva();
        reservas.setVisible(true);
        escritorio.add(reservas);
        escritorio.moveToFront(reservas);  
    }//GEN-LAST:event_jMenuItemAnularReservasActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        Listar_Reservas reservas = new Listar_Reservas();
        reservas.setVisible(true);
        escritorio.add(reservas);
        escritorio.moveToFront(reservas);  
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItemCargaMozoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCargaMozoActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        Cargar_Mozo cargaMozo = new Cargar_Mozo();
        cargaMozo.setVisible(true);
        escritorio.add(cargaMozo);
        escritorio.moveToFront(cargaMozo);  
    }//GEN-LAST:event_jMenuItemCargaMozoActionPerformed

    private void jMenuItemEliminarMozoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemEliminarMozoActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        Eliminar_Mozo eliminar_Mozo = new Eliminar_Mozo();
        eliminar_Mozo.setVisible(true);
        escritorio.add(eliminar_Mozo);
        escritorio.moveToFront(eliminar_Mozo);  
    }//GEN-LAST:event_jMenuItemEliminarMozoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu_principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItemAnularReservas;
    private javax.swing.JMenuItem jMenuItemCargaMozo;
    private javax.swing.JMenuItem jMenuItemEliminarMozo;
    private javax.swing.JMenuItem jMenuItemReservas;
    private javax.swing.JMenuItem jMenuItem_CobrarPedi;
    private javax.swing.JMenuItem jMenuItem_CrearPedi;
    private javax.swing.JMenuItem jMenuItem_Ganancias;
    private javax.swing.JMenu jMenu_Pedidos;
    private javax.swing.JMenu jMenu_Reservas;
    // End of variables declaration//GEN-END:variables

    
}

