/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */

package vistas;

import appfinal_grupo7.AccesoADatos.Detalle_PedidoData;
import appfinal_grupo7.AccesoADatos.MeseroData;
import appfinal_grupo7.AccesoADatos.PedidoData;
import appfinal_grupo7.AccesoADatos.ProductoData;
import appfinal_grupo7.Entidades.Detalle_Pedido;
import appfinal_grupo7.Entidades.Producto;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author bruno
 */
public class Procesar_Pedido extends javax.swing.JInternalFrame {
    
    private DefaultTableModel modelo;
    private ArrayList<Detalle_Pedido> lista_detalle;
    
    private PedidoData pedido;
    private Detalle_PedidoData detalle;
    private MeseroData mesero;
    private int id_pedido;
    
    private Color color;

    


    /** Creates new form Modificar_Pedido */
    public Procesar_Pedido() {
        initComponents();
        modelo = new DefaultTableModel();
        detalle = new Detalle_PedidoData();   
        mesero = new MeseroData();
        pedido = new PedidoData();
        
        armarTabla();
        color = jButton_Salir.getBackground(); 
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel_NumPedido = new javax.swing.JLabel();
        jTextField_NumPedido = new javax.swing.JTextField();
        jButton_Buscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Detalle = new javax.swing.JTable();
        jTextField_Total = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton_Cobrar = new javax.swing.JButton();
        jButton_Cancelar = new javax.swing.JButton();
        jButton_Limpiar = new javax.swing.JButton();
        jButton_Salir = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(400, 650));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("Procesar Pedido");

        jLabel_NumPedido.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_NumPedido.setText("Introduzca el n° de pedido:");

        jTextField_NumPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_NumPedidoActionPerformed(evt);
            }
        });

        jButton_Buscar.setText("¡Buscar!");
        jButton_Buscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton_BuscarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton_BuscarMouseExited(evt);
            }
        });
        jButton_Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_BuscarActionPerformed(evt);
            }
        });

        jTable_Detalle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable_Detalle);

        jTextField_Total.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTextField_Total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_TotalActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("EL total del pedido es:");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("¿Que desea hacer?");

        jButton_Cobrar.setText("Cobrar pedido");
        jButton_Cobrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton_CobrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton_CobrarMouseExited(evt);
            }
        });
        jButton_Cobrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CobrarActionPerformed(evt);
            }
        });

        jButton_Cancelar.setText("Cancelar pedido");
        jButton_Cancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton_CancelarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton_CancelarMouseExited(evt);
            }
        });
        jButton_Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CancelarActionPerformed(evt);
            }
        });

        jButton_Limpiar.setText("Limpiar");
        jButton_Limpiar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton_LimpiarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton_LimpiarMouseExited(evt);
            }
        });
        jButton_Limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_LimpiarActionPerformed(evt);
            }
        });

        jButton_Salir.setText("Salir");
        jButton_Salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton_SalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton_SalirMouseExited(evt);
            }
        });
        jButton_Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jButton_Salir)
                                .addComponent(jLabel3)))
                        .addGap(114, 114, 114))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton_Cobrar)
                            .addComponent(jButton_Limpiar))
                        .addGap(18, 18, 18)
                        .addComponent(jButton_Cancelar)
                        .addGap(91, 91, 91))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel_NumPedido)
                        .addGap(49, 49, 49)
                        .addComponent(jTextField_NumPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addComponent(jButton_Buscar))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jTextField_Total, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(148, 148, 148))
            .addGroup(layout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_NumPedido)
                    .addComponent(jTextField_NumPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton_Buscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jTextField_Total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Cancelar)
                    .addComponent(jButton_Cobrar))
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Limpiar)
                    .addComponent(jButton_Salir))
                .addGap(40, 40, 40))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_NumPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_NumPedidoActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTextField_NumPedidoActionPerformed

    private void jButton_BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_BuscarActionPerformed
        // TODO add your handling code here:
        try {
            cargarTabla(leerPedido());
            
            jTextField_Total.setText("$ " + mostrarTotal() + "");
            
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Debe ingresar un valor válido");
            jButton_Cobrar.setEnabled(false);
            jButton_Cancelar.setEnabled(false);
        }
         catch (NullPointerException  e) {
            JOptionPane.showMessageDialog(null, "No hay registros de ese pedido (null)");
            jButton_Cobrar.setEnabled(false);
            jButton_Cancelar.setEnabled(false);
        }
    }//GEN-LAST:event_jButton_BuscarActionPerformed

    private void jTextField_TotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_TotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_TotalActionPerformed

    private void jButton_CobrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CobrarActionPerformed
        // TODO add your handling code here:
        mesero.cobrarPedido(leerPedido());        
    }//GEN-LAST:event_jButton_CobrarActionPerformed

    private void jButton_SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SalirActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton_SalirActionPerformed

    private void jButton_LimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_LimpiarActionPerformed
        // TODO add your handling code here:
        limpiarTabla();
        jTextField_NumPedido.setText("");
        jTextField_Total.setText("");
        jButton_Cobrar.setEnabled(true);
        jButton_Cancelar.setEnabled(true);
    }//GEN-LAST:event_jButton_LimpiarActionPerformed

    private void jButton_CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CancelarActionPerformed
        // TODO add your handling code here:
        int respuesta = JOptionPane.showConfirmDialog(null, "Si cancela el pedido, se eliminará de la base de datos ¿Desea continuar?", "Confirmación", JOptionPane.YES_NO_OPTION);

        if (respuesta == JOptionPane.YES_OPTION) {
            detalle.eliminarDetallesPorPedido(id_pedido);
            mesero.eliminarPedido(id_pedido);
        } else if (respuesta == JOptionPane.NO_OPTION) {
            JOptionPane.showMessageDialog(null, "Aaaah arrugaste");
        }        
    }//GEN-LAST:event_jButton_CancelarActionPerformed

    private void jButton_BuscarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_BuscarMouseEntered
        // TODO add your handling code here:
        jButton_Buscar.setBackground( Color.orange.darker());
    }//GEN-LAST:event_jButton_BuscarMouseEntered

    private void jButton_CancelarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_CancelarMouseEntered
        // TODO add your handling code here:
        jButton_Cancelar.setBackground( Color.orange.darker());
    }//GEN-LAST:event_jButton_CancelarMouseEntered

    private void jButton_LimpiarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_LimpiarMouseEntered
        // TODO add your handling code here:
        jButton_Limpiar.setBackground( Color.orange.darker());
    }//GEN-LAST:event_jButton_LimpiarMouseEntered

    private void jButton_SalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_SalirMouseExited
        // TODO add your handling code here:
        jButton_Salir.setBackground(color);
    }//GEN-LAST:event_jButton_SalirMouseExited

    private void jButton_SalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_SalirMouseEntered
        // TODO add your handling code here:
        jButton_Salir.setBackground( Color.red.darker());
    }//GEN-LAST:event_jButton_SalirMouseEntered

    private void jButton_CobrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_CobrarMouseEntered
        // TODO add your handling code here:
        jButton_Cobrar.setBackground( Color.orange.darker());
    }//GEN-LAST:event_jButton_CobrarMouseEntered

    private void jButton_CobrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_CobrarMouseExited
        // TODO add your handling code here:
        jButton_Cobrar.setBackground(color);
    }//GEN-LAST:event_jButton_CobrarMouseExited

    private void jButton_CancelarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_CancelarMouseExited
        // TODO add your handling code here:
        jButton_Cancelar.setBackground(color);
    }//GEN-LAST:event_jButton_CancelarMouseExited

    private void jButton_LimpiarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_LimpiarMouseExited
        // TODO add your handling code here:
        jButton_Limpiar.setBackground(color);
    }//GEN-LAST:event_jButton_LimpiarMouseExited

    private void jButton_BuscarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_BuscarMouseExited
        // TODO add your handling code here:
        jButton_Buscar.setBackground(color);
    }//GEN-LAST:event_jButton_BuscarMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Buscar;
    private javax.swing.JButton jButton_Cancelar;
    private javax.swing.JButton jButton_Cobrar;
    private javax.swing.JButton jButton_Limpiar;
    private javax.swing.JButton jButton_Salir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel_NumPedido;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_Detalle;
    private javax.swing.JTextField jTextField_NumPedido;
    private javax.swing.JTextField jTextField_Total;
    // End of variables declaration//GEN-END:variables

    private void armarTabla(){
        ArrayList<Object> cabecera = new ArrayList<>();
        cabecera.add("ID");
        cabecera.add("Producto");
        cabecera.add("Precio");
        cabecera.add("Cantidad");
        cabecera.add("Subtotal");
        
        for (Object object : cabecera) {
            modelo.addColumn(object);
        }
        jTable_Detalle.setModel(modelo);
    }
    
    private void cargarTabla(int id_pedido){                
        lista_detalle= (ArrayList<Detalle_Pedido>) detalle.buscarDetallePorPedido(id_pedido);
        limpiarTabla();
        
        if (pedido.buscarPedidoPorID(id_pedido) == null) {
            JOptionPane.showMessageDialog(null, "Este pedido se eliminó.");
            jButton_Cobrar.setEnabled(false); 
            jButton_Cancelar.setEnabled(false);
        }
        
        
        if (pedido.buscarPedidoPorID(id_pedido).getEstado() == 0) {
            JOptionPane.showMessageDialog(null, "Este pedido ya se cobró.");
            jButton_Cobrar.setEnabled(false); 
            jButton_Cancelar.setEnabled(false);
        }
        
        for (Detalle_Pedido deta : lista_detalle) {   
            modelo.addRow(new Object[] {deta.getId_detalle(), deta.getProducto().getNombre(), deta.getProducto().getPrecio_unitario(),
            deta.getCantidad(), deta.getCantidad()*deta.getProducto().getPrecio_unitario()});
        } 
    }
    
    private void limpiarTabla() {
        if (modelo != null) {
            modelo.setRowCount(0); 
        }
    }
    
    private double mostrarTotal() {
        return detalle.calcularTotalDetalle(leerPedido());
    }
    
    private int leerPedido(){
        return id_pedido = Integer.parseInt(jTextField_NumPedido.getText());
    }    
}